### ISSUE TITLE
Make -y switch optional in command-line tools

### ISSUE THREAD

**Issue by tturocy** [chadwickbureau/chadwick#17]
It appears the DiamondWare tools operate correctly even without the -y switch being specified (presumably because it manages to infer the year from the game date).

It would be useful to investigate implementing such a facility, where year would be inferred if -y is not specified.

**Comment by jerryword** [comment]
The cwtools work as long as there is a team file in the directory from which they are run: `touch team && cwgame event/asg/2018AS.EVE`

**Comment by tturocy** [comment]
But that is exactly (part of) the bug @jerryword.  That should not work as it is not valid in the DiamondWare system.

**Comment by tturocy** [comment]
Based on subsequent conversations, it's been determined that running the DiamondWare tools without the -y switch is considered not a good idea; even though a bare "TEAM" file is accepted it is vestigial and deprecated.  Therefore we won't be doing this.
