### ISSUE TITLE
Pitcher Wins in cwdaily

### ISSUE THREAD

**Issue by zamorarr** [chadwickbureau/chadwick#21]
Hi! Thanks for this awesome library. I'm really enjoying the `cwdaily` tool - its super fast and the csv output is great. Is it possible to output pitcher wins (ex. "P_WIN") as one of the fields? Or is there another tool I should be using for this stat?

**Comment by tturocy** [comment]
This was entirely an editing error that led to some categories getting dropped off.  This has been corrected in 2111332.
