### ISSUE TITLE
Suppressing warning messages

### ISSUE THREAD

**Issue by jerryword** [chadwickbureau/chadwick#22]
Is there a way to suppress warning messages generated by the cwtools? cwgame is throwing `Warning: Invalid integer value 'unknown'` causing my downstream process to fail.

**Comment by tturocy** [comment]
Those are written to stderr, so they should not be causing you any problems if you are piping properly.

Suppressing messages like that is usually not a good idea, especially as it means you're creating invalid files somehow.

**Comment by jerryword** [comment]
Yes, you're quite correct. Not sure what I was thinking. My application is piping cwtool output directly into an external table, so my solution was to redirect STDERR to a log file.
