### ISSUE TITLE
Missing detail in cwbox output for POCS plays

### ISSUE THREAD

**Issue by kennyjackelen** [chadwickbureau/chadwick#27]
For some plays coded like `POCS2(136)`, cwbox generates a line like this:

`<caughtstealing runner="sosas001" pitcher="ruscg001" catcher="osikk001" inning="3" half="1" base="2" pickoff="0"/>`

Primarily, `Pickoff="0"` is inaccurate, but we also don't get any information about the other fielders involved.

I've noticed that this does not happen with every single play coded as `POCS2(136)` so there must be another factor involved, but I'm not sure what it is. CHN200305070 is a good example game to test with to see the issue with this line (produces the above sample output):

`play,6,1,bellm002,00,1,POCS2(136)`

Steps to reproduce:
```
wget https://www.retrosheet.org/events/2003eve.zip
unzip 2003eve.zip CHN2003.ROS MIL2003.ROS 2003CHN.EVN TEAM2003
cwbox -i CHN200305070 -y 2003 -X 2003CHN.EVN
```

**Comment by tturocy** [comment]
I looked at the same in question, which I assume is CHN200305070 - you didn't say but it matches the runner, pitcher, catcher and inning.  On that play Sosa was out on a straight caught stealing and was not picked off.  So why is Pickoff="0" inaccurate?  Or am I looking at the wrong play?

I have never seen a boxscore that lists all the fielders involved on a caught stealing play, only the pitcher and/or catcher.

**Comment by kennyjackelen** [comment]
Sorry - I got my brain all tied in knots testing different plays and got mixed up as I was writing the bug.  You can disregard the Pickoff="0" problem as I got the two output lines of the boxscore mixed up.

We had a user request that we show more info about the fielders for these, but if that's out of scope for cwbox, that's okay.  I would not have submitted an issue except that I had convinced myself that incorrectly that there was a separate functional problem.

**Comment by tturocy** [comment]
I would think that listing all the fielders on those plays would be out of scope for a boxscore.  Why list fielders on those plays but not other types of plays?   And, that's available in the play-by-play already...
