### ISSUE TITLE
Distinguish 0-0 counts from missing count data

### ISSUE THREAD

**Issue by droher** [chadwickbureau/chadwick#33]
There are 150,000+ plays for which Retrosheet has count data, but no pitch sequence data. For at bats that are at least two pitches long, it is easy to distinguish between completely missing pitch data and partial pitch data. However, because missing ball/strike counts are interpolated with 0, it doesn't seem to be possible to distinguish the `??` case from the `00` case once the data has been processed by cwevent. (See `BOS191210090` for a few examples). Would it be possible to add a flag or code indicating the presence/absence of count data?

**Comment by tturocy** [comment]
This is the behaviour specified by BEVENT, so in the first instance it would be Dave Smith you would want to talk to about proposing a change to this behaviour.

We view the behaviour of the BEVENT fields as sacrosanct, even if they are not the design choice we would have made.

**Comment by droher** [comment]
I was thinking that this would be in the extension fields as opposed to a BEVENT field behavior change.

**Comment by tturocy** [comment]
This is implemented in v0.9.2
