### ISSUE TITLE
generalizing for manual retrosheets 

### ISSUE THREAD

**Issue by anthonyscorrea** [chadwickbureau/chadwick#35]
I am looking to use this tool for aggregating data in a non-MLB team.

This may be tricky, how does one record in a sheet an “extra hitter” position. It is equivalent to a fielding position, but the player only bats. If I give this position a unused position number, does it break chadwick? Does a lineup of 10 batters break it?

**Comment by tturocy** [comment]
The assumptions of nine-person batting orders and the MLB DH rule are baked very deeply into the tools.  They're not going to be compatible with EHs.

**Comment by anthonyscorrea** [comment]
thanks for the reply.
