### ISSUE TITLE
Problems compliling chadwick 0.9.1 on Linux

### ISSUE THREAD

**Issue by mdj6248** [chadwickbureau/chadwick#41]
I downloaded the source code for 0.9.1 to my Ubuntu system, but it doesn't include a configure file to build the makefiles. I tried generating one with autoconf, but get an error beginning with "configure.ac:28: error: possibly undefined macro: AM_INIT_AUTOMAKE".

I can't seem to locate any documentation for building the package that goes deeper than "./configure; make; make install'. Pointers to docs or assistance in building this version would be greatly appreciated.

**Comment by tturocy** [comment]
I cannot reproduce this.  I just downloaded chadwick-0.9.1.tar.gz to check, and indeed there is a configure script.

In fact, it would be just about impossible for there not to be a configure script, because it's the configure script that makes the tarball....

**Comment by mdj6248** [comment]
That's what I expected, but when I pull down the zip for 0.9.1, here's what I see in archive manager:
![image](https://user-images.githubusercontent.com/30967715/139850931-9c315b1a-5abe-48c2-badc-120cb8cc57d4.png)

**Comment by tturocy** [comment]
Why does this think it's a zip file? The source release is a tarball.

**Comment by mdj6248** [comment]
The problem may be that I'm not that familiar with github, but the assets page for version 0.9.1 shows source code in both zip and tarball formats. If the right answer is "grab the tarball instead" I'm fine with that.

**Comment by tturocy** [comment]
chadwick-0.9.1.tar.gz.  chadwick-0.9.1-win.zip would be windows binaries.

**Comment by mdj6248** [comment]
Thanks. I pulled down the right package and was able to compile things. One last possibly dumb question. I have a set of 2019 EVA files from Rotosheet, and when I try to run (for instance) "cwevent 2019ANA.EVA" it gives an error of "Can't find teamfile (team)". Am I misreading the usage message? It seems like that should work.

**Comment by epistemik** [comment]
The six Chadwick 'cwXXX' command line tools: cwdaily, cwbox, cwevent, cwgame, cwsub, cwcomment
    ALL have the same restrictions:
    1) tool MUST be run from a folder containing the required TEAM file, e.g. TEAM1963
    2) despite being described as an 'option' in the help text, the parameter '-y year' MUST BE specified or the tool CANNOT find the TEAM file!
    3) the required event file, e.g. 1963KC1.EVA, also MUST be in the current folder and MUST appear as the LAST parameter to the command
