### ISSUE TITLE
README.md: installation instructions

### ISSUE THREAD

**Issue by aleph777** [chadwickbureau/chadwick#47]
The installation instructions are incomplete. They should look like:

1. sudo apt install libtool-bin
2. libtoolize 
3. ./ltconfig ltmain.sh
4. aclocal
5. autoconf 
6. automake
7. ./configure
8. make
9. sudo make install

**Comment by tturocy** [comment]
No.  autotools would only be required if someone wants to build from the repository for development purposes.
