### ISSUE TITLE
Need Help with Install

### ISSUE THREAD

**Issue by jensenyamane** [chadwickbureau/chadwick#52]
I have a Windows and am getting this when I run baseballr::chadwick_ld_library_path():
Warning: running command '"find" C:/Users/jense/OneDrive/Documents/R/Baseball Analytics/Projects -name "libchadwick*"' had status 1Error in if (!chadwick_find_lib() %in% old_ld_library_paths) { : 
  the condition has length > 1

baseballr::chadwick_is_installed is TRUE so I don't know what I've done wrong.

**Comment by tturocy** [comment]
This is not a Chadwick issue - you need to direct this to the maintainers of the R package.
