### ISSUE TITLE
cwevent does not correctly mark PIT_ID in instances where the starting pitcher pitches to the first batter but is then removed during the first batter

### ISSUE THREAD

**Issue by bwalko** [chadwickbureau/chadwick#53]
For Steven Matz start on 22 May 2022 (PIT202205220), cwevent generates a PIT_ID and RESP_PIT_ID for Angel Rondon for Event 7, when Ke'Bryan Hayes strikes out.  The event data shows Matz throwing several pitches before being removed from the game.

id,PIT202205220
version,2
.. removed some lines...
start,edmat001,"Tommy Edman",0,1,6
start,gormn001,"Nolan Gorman",0,2,4
start,arenn001,"Nolan Arenado",0,3,10
start,yepej001,"Juan Yepez",0,4,3
start,donob001,"Brendan Donovan",0,5,9
start,sosae001,"Edmundo Sosa",0,6,5
start,dickc002,"Corey Dickerson",0,7,7
start,kniza001,"Andrew Knizner",0,8,2
start,badeh001,"Harrison Bader",0,9,8
**start,matzs001,"Steven Matz",0,0,1**
start,hayek001,"Ke'Bryan Hayes",1,1,5
start,reynb001,"Bryan Reynolds",1,2,8
start,chavm001,"Michael Chavis",1,3,3
start,gameb001,"Ben Gamel",1,4,7
start,castd004,"Diego Castillo",1,5,9
start,tsuty001,"Yoshi Tsutsugo",1,6,10
start,castr006,"Rodolfo Castro",1,7,6
start,vanmj001,"Josh VanMeter",1,8,4
start,heint001,"Tyler Heineman",1,9,2
start,wilsb003,"Bryse Wilson",1,0,1
play,1,0,edmat001,12,BFFX,S9/G4
play,1,0,gormn001,12,CBS>B,SB2
play,1,0,gormn001,22,CBS>B.FFX,D8/L8XD+.2-H
play,1,0,arenn001,00,X,9/F89XD
play,1,0,yepej001,12,CBSS,K
play,1,0,donob001,01,CX,7/F7L
**play,1,1,hayek001,22,CFBB,NP**
sub,ronda001,"Angel Rondon",0,0,1
play,1,1,hayek001,22,CFBB.T,K
play,1,1,reynb001,32,BBBCFB,W

**Comment by tangotiger** [comment]
This is not a bug.

As per the documentation:
"The batter and pitcher fields always give the identity of the batter and pitcher in the game at the time of the event; the result batter and result pitcher give the batter and pitcher credited or charged with the event."
https://chadwick.readthedocs.io/en/latest/cwevent.html#cwtools-cwevent-resplayers

In other words, whoever is the LAST pitcher for that event is noted as PIT_ID.  RESP_PIT_ID is whoever is officially charged with that event.

**Comment by bwalko** [comment]
How would you be able to tell that Matz appeared in the game using the Chadwick tools?  

I looked at the Game level data, which lists him as the starting pitcher, but then you have an instance where Blake Snell was in a similar situation in 2022 - but he didn't throw any pitches in the game. 

If I used the logic Matz was the starter per the game-level stats even though he is not recorded as a pitcher in the event-level stats, this same logic would credit Snell with a start - which the MLB does not credit him for.

**Comment by tturocy** [comment]
As noted, no bug here, the output is correct.
