### ISSUE TITLE
Enhancement for a field to indicate the BAT_ID and PIT_ID at the start of the event

### ISSUE THREAD

**Issue by bwalko** [chadwickbureau/chadwick#54]
**Enhancement for a field to indicate the BAT_ID and PIT_ID at the start of the event**

Both will have value, and the PIT_ID version would address a situation where it is impossible to derive the correct Games Started for a player using the resulting data from cwevent.

Create a field that identifies the pitcher at the start of an event so that one can differentiate between a game like Blake Snell (ARI202204100) where he was not credited with a start by MLB and Steven Matz start on 22 May 2022 (PIT202205220) where he was credited with a start by MLB.

cwevent generates a PIT_ID and RESP_PIT_ID for Angel Rondon for Event 7 of PIT202205220, when Ke'Bryan Hayes strikes out. The event data shows Matz throwing several pitches before being removed from the game. The generated Event and Game data for PIT202205220 and ARI202204100 makes it impossible to correctly get both Snell and Matz Games Started. 

Currently, we have two ways of looking at the data that cwevent and cwgame provide, and each way provides an incorrect result.
If you assume that the Game data indicates the scheduled starter pitched, then Snell will be incorrectly given a start. 
If you assume the Event data for the first event versus the Home/Away batters indicates the starting pitcher, then Matz will incorrectly not be credited with a start.

id,PIT202205220
version,2
.. removed some lines...
start,edmat001,"Tommy Edman",0,1,6
start,gormn001,"Nolan Gorman",0,2,4
start,arenn001,"Nolan Arenado",0,3,10
start,yepej001,"Juan Yepez",0,4,3
start,donob001,"Brendan Donovan",0,5,9
start,sosae001,"Edmundo Sosa",0,6,5
start,dickc002,"Corey Dickerson",0,7,7
start,kniza001,"Andrew Knizner",0,8,2
start,badeh001,"Harrison Bader",0,9,8
**start,matzs001,"Steven Matz",0,0,1**
start,hayek001,"Ke'Bryan Hayes",1,1,5
start,reynb001,"Bryan Reynolds",1,2,8
start,chavm001,"Michael Chavis",1,3,3
start,gameb001,"Ben Gamel",1,4,7
start,castd004,"Diego Castillo",1,5,9
start,tsuty001,"Yoshi Tsutsugo",1,6,10
start,castr006,"Rodolfo Castro",1,7,6
start,vanmj001,"Josh VanMeter",1,8,4
start,heint001,"Tyler Heineman",1,9,2
start,wilsb003,"Bryse Wilson",1,0,1
play,1,0,edmat001,12,BFFX,S9/G4
play,1,0,gormn001,12,CBS>B,SB2
play,1,0,gormn001,22,CBS>B.FFX,D8/L8XD+.2-H
play,1,0,arenn001,00,X,9/F89XD
play,1,0,yepej001,12,CBSS,K
play,1,0,donob001,01,CX,7/F7L
**play,1,1,hayek001,22,CFBB,NP
sub,ronda001,"Angel Rondon",0,0,1
play,1,1,hayek001,22,CFBB.T,K**
play,1,1,reynb001,32,BBBCFB,W

**Comment by bwalko** [comment]
The SUBS data gives the same kind of results - both Snell and Matz look identical.  So you couldn't use it to discern whether one got credited a start and one did not.

If anything, Matz could be wrong, it lists the event ID that he was removed as Event 6 (presumably meant to indicate after Event 6 ended), but he was removed in the middle of Event 7. (Like Matz being removed at Event 6, Event 3 is the one preceding the first batter Snell was to pitch to)

GAME_ID|INN_CT|BAT_HOME_ID|SUB_ID|SUB_HOME_ID|SUB_LINEUP_ID|SUB_FLD_CD|REMOVED_ID|REMOVED_FLD_CD|EVENT_ID
ARI202204100|1|1|crisn001|0|0|1|snelb001|1|3
PIT202205220|1|1|ronda001|0|0|1|matzs001|1|6

**Comment by tturocy** [comment]
The version of cwsub about to be released has extra metadata which includes the pitch state at the time of the substitution.

**Comment by bwalko** [comment]
Thanks! What will this metadata look like, I am happy to provide an extra set of eyes.  (The work I am doing is already incorporating SUBS and COMMENTS in concert with EVENT AND GAME to compile the proper data).

This is true that the rules have changed over time, but it would at least be a way to have SQL or other code that does a different interpretation based on the year.
