### ISSUE TITLE
cwevent not working in ubuntu in WSL

### ISSUE THREAD

**Issue by billbrad** [chadwickbureau/chadwick#57]
Hello, 

I downloaded and installed chadwick-0.1.0 exactly as described in the instructions. However when I run 

`cwevent -y 2023 -f 0-96 2023*.EV* > all2023.csv`

I get the following error:

`cwevent: error while loading shared libraries: libchadwick.so.0: cannot open shared object file: No such file or directory`

There is no information on this type of error in the Chadwick documentation.

**Comment by beanumber** [comment]
You have to set the `LD_LIBRARY_PATH` environment variable. The R code here might help:

https://github.com/BillPetti/baseballr/blob/master/R/chadwick_installation.R

**Comment by billbrad** [comment]
Working great now! Thank you for the help!
