### ISSUE TITLE
`cwgame`: game start time (field 4) does not differentiate between AM and PM

### ISSUE THREAD

**Issue by PatrickNorton** [chadwickbureau/chadwick#58]
The game start time of `cwgame` is in 12-hour format, which does not differentiate between AM and PM. The day/night flag is not useful in differentiating as there are several time/day combinations that have games at both AM and PM times. Since the Retrosheet data has AM/PM included in it, it would be nice if the game start time was in 24-hour format, or there was an AM/PM flag added to the output.

**Comment by tturocy** [comment]
Because cwgame does what BGAME does, this cannot be changed.

**Comment by PatrickNorton** [comment]
Would it be possible to add an extended field with the 24-hour time then?
